kapp_platform_homepage:
    path:     /hello/{name}
    defaults: { _controller: KappPlatformBundle:Default:index }

hello_the_world:
    path:     /hello-world
    defaults: { _controller: KappPlatformBundle:Advert:index }

oc_platform_home:
    path:      /
    defaults:  { _controller: KappPlatformBundle:Advert:index }
    
oc_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: KappPlatformBundle:Advert:view }
    
oc_platform_add:
    path:      /add
    defaults:  { _controller: KappPlatformBundle:Advert:add }

oc_platform_view_slug:
    path:      /{year}/{slug}.{format}
    defaults:  { _controller: KappPlatformBundle:Advert:viewSlug,format: html }
    requirements:
        year:   \d{4}
        format: html|xml