kapp_platform_homepage:
    path:     /hello/{name}
    defaults: { _controller: KappPlatformBundle:Default:index }

hello_the_world:
    path:     /hello-world
    defaults: { _controller: KappPlatformBundle:Advert:index }

kapp_platform_home:
    path:      /{page}
    defaults:  { _controller: OCPlatformBundle:Advert:index, page: 1 }
    requirements:
        page: \d*
    
kapp_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:view }
    requirements:
        id: \d+
    
kapp_platform_add:
    path:      /add
    defaults:  { _controller: OCPlatformBundle:Advert:add }

kapp_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:edit }
    requirements:
        id: \d+

kapp_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:delete }
    requirements:
        id: \d+

kapp_platform_view_slug:
    path:      /{year}/{slug}.{format}
    defaults:  { _controller: KappPlatformBundle:Advert:viewSlug,format: html }
    requirements:
        year:   \d{4}
        format: html|xml